### ISSUE TITLE
DB 접근 로직 테스트 정의

### ISSUE THREAD

**Issue by dooyong2** [dooyong2/solo-project-board-admin#2]
어드민 프로젝트가 DB를 사용할 수 있도록 환경을 구성하고 테스트를 정의한다

## TODO

- [x] db만들기
- [x] 계정 권한 부여
- [x] IDE 접근 환경 꾸미기
- [ ] repository 코드 작성
- [ ] 관련 테스트 작성
